name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on release events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: ./.github/workflows/composite-action
      - run: pip install black
      - run: black --check src
      - run: black --check tests
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: ./.github/workflows/composite-action
      - run: pip install pylint
      - run: pylint src
      - run: |
          if [ -f "./tests/.pylintrc" ]; then
            pylint --rcfile tests/.pylintrc tests
          else
            pylint tests
          fi
  test:
    runs-on: ubuntu-latest
    needs: [black, pylint]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: ./.github/workflows/composite-action
      - run: |
          python setup.py test
